### PR TITLE
support arrays and optional fields in function call schema

### PR DESCRIPTION
**Pull request by jb17q**
this PR

* updates oaiParams to include the items property in arrays to match openAI's function call schema requirements (fixes issue https://github.com/livekit/agents-js/issues/124)
* updates oaiParams to omit optional fields from the required section of the generated openAI function call schema
* adds unit tests for oaiParams

### CODE REVIEW

**Comment by nbsp** [comment]
sorry, rebased v0.4.0 and it caused ugly conflicts. can you rebase your branch on top of 0.4.0 so it's just the latest two commits? i would do it but GitHub doesn't let me force-push to fork branches

**Comment by jb17q** [comment]
> sorry, rebased v0.4.0 and it caused ugly conflicts. can you rebase your branch on top of 0.4.0 so it's just the latest two commits? i would do it but GitHub doesn't let me force-push to fork branches
> 
> `git rebase v0.4.0` then just `git rebase --skip` until it stops complaining. then force push

done

**Comment by jb17q** [comment]
> sorry, rebased v0.4.0 and it caused ugly conflicts. can you rebase your branch on top of 0.4.0 so it's just the latest two commits? i would do it but GitHub doesn't let me force-push to fork branches
> 
> `git rebase v0.4.0` then just `git rebase --skip` until it stops complaining. then force push

done

**Review by nbsp — APPROVED** [review]

**Comment by nbsp** [comment]
thanks! 🙌

**Pull request merged**
